id: P009153
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:25:33.187809
source_metadata:
  id: bdr:W1KG21595
  title: རྒྱུན་མཐོང་མོ་ནད་འགོག་བཅོས།
  author: ''
  volumes:
    a9852f4aba8248dc834f2c84faf6b85c:
      image_group_id: I1KG21689
      title: ''
      volume_number: 1
      total_pages: 118
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
