id: I09649023
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T13:28:24+00:00'
last_modified: '2022-06-08T08:59:56.184346+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21595
  title: རྒྱུན་མཐོང་མོ་ནད་འགོག་བཅོས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    27E5:
      image_group_id: I1KG21689
      title: ''
      total_pages: 118
      order: 1
      base_file: 27E5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
